# .prettierrc.toml

# TODO: Something in this is blocking the hydration

# bracketSameLine = false
# endOfLine = "lf"
# htmlWhitespaceSensitivity = "css"
# parser = "html"
# printWidth = 80
# singleAttributePerLine = true
# tabWidth = 2
# useTabs = false
