[package]
authors = ["David Wallace Croft <david@croftsoft.com>"]
# Use the categories from https://crates.io/categories
# categories = ["category-name"]
description = "Dallas Rust Users Meetup website using Dioxus"
edition = "2021"
homepage = "https://www.dallasrust.org/"
keywords = ["dioxus"]
license = "MIT"
name = "dioxus-prototype"
publish = false
readme = "README.md"
repository = "https://github.com/dallasrust/website-dioxus"
version = "0.0.0-SNAPSHOT"

[dependencies]
chrono = "0.4.26"
console_error_panic_hook = "0.1.7"
dioxus = "0.4.0"
dioxus-router = "0.4.1"
dioxus-web = "0.4.0"
gloo-history = "0.1.5"
log = "0.4.19"
once_cell = "1.18.0"
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.103"
wasm-bindgen = { version = "0.2.87", features = ["enable-interning"] }
wasm-logger = "0.2.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
