[application]

# dioxus project name
name = "website-dioxus"

# default platfrom
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Dallas Rust Users Meetup"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# index_on_404 = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["stylesheet.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []

[bundler]
# Bundle identifier
identifier = "org.dallasrust.app.website-dioxus"

# Bundle publisher
publisher = "website-dioxus"

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["public/*"]

# Bundle copyright
copyright = "Copyright 2023 Dallas Rust Users Meetup"

# Bundle category
category = "Utility"

# Bundle short description
short_description = "Dallas Rust Users Meetup website using Dioxus"

# Bundle long description
long_description = """
Dallas Rust Users Meetup website using Dioxus
"""
